/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/Dialogs/ModelDialogPersistent copy.vue')['default']
    DrawerNavegation: typeof import('./src/components/DrawerNavegation.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Footter: typeof import('./src/components/Footter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ModelAlertPersistent: typeof import('./src/components/Dialogs/ModelAlertPersistent.vue')['default']
    ModelDialogPersistent: typeof import('./src/components/Dialogs/ModelDialogPersistent.vue')['default']
    ModelProgress: typeof import('./src/components/Dialogs/ModelProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
